### ISSUE TITLE
Add a rescan button to the UI

### ISSUE THREAD

**Issue by kbekus** [Maker-Management-Platform/mmp-ui#107]
hi there, great to see you take your work on stlib and turn it into this. Is it possible to get a 'rescan' button on the UI somewhere please?  I add files to my library which is a samba share. How can I make MMP aware of these files without stopping and restarting the docker containers?

**Comment by EduardoOliveira** [comment]
This has been in the back of my mind since the beginning... Hop to add it by v1.1.0
