### ISSUE TITLE
Delete project Operation

### ISSUE THREAD

**Issue by nickkjordan** [Maker-Management-Platform/mmp-ui#70]
An option to delete a project under the Operations tab

**Comment by EduardoOliveira** [comment]
Hi, thank you for the issue.
The delete function was one of the reasons the Operations tab was created, but I never came around to implement it.
It will be implemented very soon.

**Comment by nickkjordan** [comment]
Sweet! thanks

**Comment by EduardoOliveira** [comment]
Hi there, the feature should be available in the :latest and the RC-1.0.0 images very soon
Could you please check it out?

**Comment by nickkjordan** [comment]
Yes, working well for me, thanks!
