### ISSUE TITLE
Option to Ignore Hidden Files?

### ISSUE THREAD

**Issue by crosbyh** [Maker-Management-Platform/mmp-ui#86]
Hello - Love what you are doing with this application so far!

I am wondering if it would be possible, either as an option or by default, to have the app ignore hidden files from the filesystem. These would be any files which begin with a "."

Reason being, some operating systems (macOS specifically) create these dotfiles to store metadata (even on network drives), and these clutter up the UI with irrelevant files, as seen in the attached screenshot.

![Screenshot 2024-01-17 at 9 02 11 AM](https://github.com/Maker-Management-Platform/mmp-ui/assets/13104810/2715d2cc-22ad-4eb8-a019-e469f2e617d3)

**Comment by EduardoOliveira** [comment]
Hi, thank you for you feedback.
I agree with you, I'll look into it

**Comment by EduardoOliveira** [comment]
This is related to #84
